// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ackqqwfxihutbqxhppvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFja3Fxd2Z4aWh1dGJxeGhwcHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDkzNjgsImV4cCI6MjA2NDg4NTM2OH0.Q3W1RRQpxZq-YOxqULr__SQgimhgRDK_ELOfIOOn86k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);